"""Self-contained HTML dashboard from paper CSVs. Regenerated by run-daily."""

from __future__ import annotations

import csv
import datetime as dt
import html
from collections import Counter, defaultdict
from pathlib import Path
from typing import Optional

from paper import DATA, MARKS, PORTFOLIO, REFERENCE_ONLY, ensure_data_dir
from paper.models import read_forecasts, read_trades, is_kelly_regime, REGIME_KELLY, REGIME_V1, HYPOTHESES
from paper.score import MIN_N, MIN_N_HYPOTHESIS, _closed_with_forecasts, _model_version, auc, brier
from spread_eval import MODEL_VERSION, MODEL_VERSION_LEGACY


def _f(x, default=None):
    try:
        if x is None or x == "":
            return default
        return float(x)
    except (TypeError, ValueError):
        return default


def _read_marks() -> list[dict]:
    if not MARKS.exists():
        return []
    with MARKS.open(newline="") as f:
        return list(csv.DictReader(f))


def _skip_bucket(reason: str) -> str:
    s = (reason or "").lower()
    if "earnings" in s:
        return "Earnings window"
    if "contracts==0" in s:
        return "Size / cap"
    if "log_growth" in s:
        return "Kelly (log growth)"
    if "insufficient rv" in s or "insufficient iv" in s:
        return "Cheapness gate (insufficient history)"
    if "rv percentile" in s or "iv-rv spread" in s or ("iv rank" in s and ">" in s):
        return "Cheapness gate (rich/expensive vol)"
    if "no forecast" in s or "market-default" in s:
        return "Market default (no forecast)"
    if "model_prob_profit" in s and "< 0.35" in s:
        return "p < 0.35 (v1)"
    if "ev" in s and "<=" in s:
        return "EV ≤ 0 (v1)"
    if "daily new-trade cap" in s:
        return "Daily cap (wanted TRADE)"
    return "Other"


def _latest_marks(marks: list[dict]) -> dict[str, dict]:
    """Last mark per trade_id (file is append-only)."""
    last: dict[str, dict] = {}
    for m in marks:
        last[m["trade_id"]] = m
    return last


def _unique_marks_by_day(marks: list[dict]) -> dict[tuple[str, str], dict]:
    out: dict[tuple[str, str], dict] = {}
    for m in marks:
        out[(m["trade_id"], m["mark_date"])] = m
    return out


def snapshot() -> dict:
    forecasts_all = read_forecasts()
    forecasts = [f for f in forecasts_all if is_kelly_regime(f)]
    v1_forecasts = [f for f in forecasts_all if not is_kelly_regime(f)]
    trades = read_trades()
    marks = _read_marks()
    closed = _closed_with_forecasts(kelly_only=True)
    closed_all = _closed_with_forecasts(kelly_only=False)
    v1_closed = [c for c in closed_all if not is_kelly_regime(c)]
    last_mark = _latest_marks(marks)
    fc_by_id = {f["forecast_id"]: f for f in forecasts_all}

    skips = [f for f in forecasts if f.get("decision") == "skip"]
    takes = [f for f in forecasts if f.get("decision") == "trade"]
    model_src = [f for f in forecasts if f.get("source") == "model"]
    wanted = [f for f in forecasts if "model=TRADE" in (f.get("rationale") or "")]
    wanted_skipped = [f for f in wanted if f.get("decision") == "skip"]

    probs = [_f(f.get("pred_prob_profit")) for f in forecasts]
    probs = [p for p in probs if p is not None]
    hist = [0, 0, 0, 0]
    for p in probs:
        if p < 0.2:
            hist[0] += 1
        elif p < 0.3:
            hist[1] += 1
        elif p < 0.4:
            hist[2] += 1
        else:
            hist[3] += 1

    skip_counts = Counter(_skip_bucket(f.get("skip_reason", "")) for f in skips)
    skip_order = [
        "Size / cap", "Earnings window", "Kelly (log growth)",
        "Cheapness gate (rich/expensive vol)", "Cheapness gate (insufficient history)",
        "Market default (no forecast)",
        "p < 0.35 (v1)", "EV ≤ 0 (v1)", "Daily cap (wanted TRADE)", "Other",
    ]
    skip_rows = [(k, skip_counts[k]) for k in skip_order if skip_counts[k]]

    # Headline calibration: kelly regime AND model_version=mc_path_v2 only (Patch 1) —
    # mc_terminal_v1 rows were scored under the biased terminal-only simulator, so
    # Brier/AUC/hit-vs-predicted-p must not mix the two. P&L below is real money
    # regardless of which simulator estimated the odds, so it stays unfiltered.
    taken_v2 = [c for c in closed if _model_version(c) == MODEL_VERSION]
    y = [c["outcome"] for c in taken_v2]
    model_p = [_f(c.get("model_prob_profit"), 0.0) for c in taken_v2]
    bm = brier(model_p, y) if taken_v2 else None
    am = auc(model_p, y) if taken_v2 else None
    hit = (sum(y) / len(y)) if y else None
    pnls = [_f(c.get("pnl"), 0.0) for c in closed]

    # Per model_version (Patch 1) — informational, shows the legacy book is excluded, not lost.
    model_version_rows = []
    for mv in (MODEL_VERSION, MODEL_VERSION_LEGACY):
        rows = [c for c in closed if _model_version(c) == mv]
        if not rows:
            model_version_rows.append({"version": mv, "n": 0, "hit": None, "brier": None})
            continue
        yv = [c["outcome"] for c in rows]
        pv = [_f(c.get("model_prob_profit"), 0.0) for c in rows]
        model_version_rows.append({
            "version": mv, "n": len(rows), "hit": sum(yv) / len(yv),
            "brier": brier(pv, yv),
        })

    # Per hypothesis (Patch 3) — localizes calibration by trade idea; headline model only.
    hypothesis_rows = []
    for h in HYPOTHESES:
        rows = [c for c in taken_v2 if str(c.get("hypothesis", "")).strip() == h]
        n_h = len(rows)
        if n_h < MIN_N_HYPOTHESIS:
            hypothesis_rows.append({"h": h, "n": n_h, "hit": None, "mean_pred": None, "brier": None})
            continue
        yh = [c["outcome"] for c in rows]
        ph = [_f(c.get("model_prob_profit"), 0.0) for c in rows]
        hypothesis_rows.append({
            "h": h, "n": n_h, "hit": sum(yh) / len(yh), "mean_pred": sum(ph) / len(ph),
            "brier": brier(ph, yh) if n_h >= MIN_N else None,
        })

    # Exit-reason mix across the whole kelly-regime closed book (any model_version) —
    # shows how positions actually resolve: TP / SL / time_stop / expiry.
    exit_counts = Counter((c.get("exit_reason") or "unknown") for c in closed)
    exit_order = ["tp", "sl", "time_stop", "expiry", "unknown"]
    exit_rows = [(k, exit_counts[k]) for k in exit_order if exit_counts[k]]

    # Today's cheapness screen (Patch 2) — live, not historical: what's investable right now.
    gate_rows = []
    try:
        from signals import cheapness_gate, rv_percentile, iv_rv_spread
        from screener import UNIVERSE
        for t in UNIVERSE:
            if t.upper() in REFERENCE_ONLY:
                continue
            try:
                passed, reason = cheapness_gate(t)
                gate_rows.append({
                    "ticker": t, "passed": passed, "reason": reason,
                    "rv_pctile": rv_percentile(t), "iv_rv": iv_rv_spread(t),
                })
            except Exception as ex:
                gate_rows.append({"ticker": t, "passed": None, "reason": f"error: {ex}",
                                  "rv_pctile": None, "iv_rv": None})
        gate_rows.sort(key=lambda r: (not r["passed"] if r["passed"] is not None else True, r["ticker"]))
    except Exception:
        gate_rows = []

    open_trades = [t for t in trades if t.get("status") == "open"]
    deployed = sum(_f(t.get("capital_at_risk"), 0.0) for t in open_trades)
    unreal = 0.0
    trade_rows = []
    for t in trades:
        m = last_mark.get(t["trade_id"], {})
        u = _f(m.get("unrealized_pnl"))
        if t.get("status") == "open" and u is not None:
            unreal += u
        opened = str(t.get("opened_utc", ""))[:10]
        closed_d = str(t.get("closed_utc", "") or "")[:10]
        same_day = bool(closed_d and opened == closed_d)
        note = ""
        mid = _f(t.get("entry_mid"))
        if same_day and t.get("exit_reason") == "sl":
            note = "same-day SL (fill/quote)"
        elif mid is not None and mid < 0:
            note = "inverted entry mid"
        elif str(m.get("carried_forward", "")).lower() == "true":
            note = m.get("flag") or "mark carried forward"
        fc = fc_by_id.get(t.get("forecast_id", ""), {})
        if not is_kelly_regime(fc):
            note = (note + "; " if note else "") + "v1 excluded from score"
        pnl = _f(t.get("pnl"))
        if t.get("status") == "open":
            pnl = u
        trade_rows.append({
            "ticker": t.get("ticker", ""),
            "opened": opened,
            "status": t.get("status", ""),
            "exit_reason": t.get("exit_reason") or "",
            "model_p": _f(t.get("model_prob_profit")),
            "entry_debit": _f(t.get("entry_debit")),
            "entry_mid": mid,
            "last_cons": _f(m.get("spread_conservative")),
            "pnl": pnl,
            "note": note,
            "same_day_sl": same_day and t.get("exit_reason") == "sl",
            "source": "open" if t.get("status") == "open" else "closed",
        })

    # MTM series: live (non-carried) marks for currently-open trades
    by_day = _unique_marks_by_day(marks)
    dates = sorted({d for (_, d) in by_day})
    live_dates = []
    for d in dates:
        any_live = False
        for t in open_trades:
            m = by_day.get((t["trade_id"], d))
            if m and str(m.get("carried_forward", "")).lower() != "true":
                any_live = True
                break
        if any_live:
            live_dates.append(d)

    mtm_series = []
    for t in open_trades:
        pts = []
        for d in live_dates:
            m = by_day.get((t["trade_id"], d))
            pts.append(_f(m.get("unrealized_pnl")) if m else None)
        mtm_series.append({"ticker": t.get("ticker", ""), "points": pts})

    dates_fc = sorted({str(f.get("ts_utc", ""))[:10] for f in forecasts_all if f.get("ts_utc")})

    return {
        "generated_utc": dt.datetime.now(dt.timezone.utc).isoformat(timespec="seconds"),
        "date_range": f"{dates_fc[0]} → {dates_fc[-1]}" if dates_fc else "—",
        "n_forecasts": len(forecasts),
        "n_v1_forecasts": len(v1_forecasts),
        "n_v1_closed": len(v1_closed),
        "regime": REGIME_KELLY,
        "n_model_src": len(model_src),
        "n_trade_decisions": len(takes),
        "n_skips": len(skips),
        "n_wanted_trade": len(wanted),
        "n_wanted_skipped": len(wanted_skipped),
        "n_closed": len(taken_v2),
        "n_closed_all_versions": len(closed),
        "n_open": len(open_trades),
        "min_n": MIN_N,
        "brier": bm,
        "auc": am,
        "hit_rate": hit,
        "closed_pnl": sum(pnls) if pnls else None,
        "n_closed_pnl": len(closed),
        "deployed": deployed,
        "unreal": unreal,
        "mean_p": (sum(probs) / len(probs)) if probs else None,
        "n_p_ge_35": sum(1 for p in probs if p >= 0.35),
        "p_hist": hist,
        "skip_rows": skip_rows,
        "trades": trade_rows,
        "mtm_dates": live_dates,
        "mtm_series": mtm_series,
        "sufficient": len(taken_v2) >= MIN_N,
        "model_version_rows": model_version_rows,
        "hypothesis_rows": hypothesis_rows,
        "exit_rows": exit_rows,
        "gate_rows": gate_rows,
    }


def _esc(x) -> str:
    return html.escape("" if x is None else str(x))


def _money(x) -> str:
    if x is None:
        return "—"
    return f"${x:,.2f}"


def _pct(x) -> str:
    if x is None:
        return "—"
    return f"{x:.1%}"


def _p(x) -> str:
    if x is None:
        return "—"
    return f"{x:.3f}"


def _bars(rows: list[tuple[str, int]], max_v: int | None = None) -> str:
    if not rows:
        return "<p class='muted'>No data</p>"
    mx = max_v or max(v for _, v in rows) or 1
    bits = []
    for label, v in rows:
        w = 100.0 * v / mx
        bits.append(
            f"<div class='bar-row'><span class='bar-label'>{_esc(label)}</span>"
            f"<div class='bar-track'><div class='bar-fill' style='width:{w:.1f}%'></div></div>"
            f"<span class='bar-n'>{v}</span></div>"
        )
    return "".join(bits)


def _svg_mtm(dates: list[str], series: list[dict]) -> str:
    usable = [s for s in series if any(p is not None for p in s["points"])]
    if not dates or not usable:
        return ""
    w, h, pad_l, pad_r, pad_t, pad_b = 640, 220, 48, 16, 16, 36
    inner_w = w - pad_l - pad_r
    inner_h = h - pad_t - pad_b
    vals = [p for s in usable for p in s["points"] if p is not None]
    lo, hi = min(vals), max(vals)
    if lo == hi:
        lo, hi = lo - 1, hi + 1
    # pad 10%
    span = hi - lo
    lo -= 0.1 * span
    hi += 0.1 * span
    span = hi - lo

    def xy(i: int, v: float) -> tuple[float, float]:
        x = pad_l + (i / max(len(dates) - 1, 1)) * inner_w
        y = pad_t + (1 - (v - lo) / span) * inner_h
        return x, y

    zero_y = pad_t + (1 - (0 - lo) / span) * inner_h
    colors = ["#7aa2f7", "#9ece6a", "#e0af68", "#bb9af7", "#f7768e"]
    paths = []
    legend = []
    for i, s in enumerate(usable):
        c = colors[i % len(colors)]
        pts = []
        for j, v in enumerate(s["points"]):
            if v is None:
                continue
            x, y = xy(j, v)
            pts.append(f"{x:.1f},{y:.1f}")
        if len(pts) >= 2:
            paths.append(f'<polyline fill="none" stroke="{c}" stroke-width="2" points="{" ".join(pts)}"/>')
        elif len(pts) == 1:
            x, y = pts[0].split(",")
            paths.append(f'<circle cx="{x}" cy="{y}" r="3.5" fill="{c}"/>')
        legend.append(
            f'<span class="swatch" style="background:{c}"></span>{_esc(s["ticker"])}'
        )

    xticks = []
    for i, d in enumerate(dates):
        x, _ = xy(i, lo)
        label = d[5:] if len(d) >= 10 else d  # MM-DD
        xticks.append(
            f'<text x="{x:.1f}" y="{h - 8}" text-anchor="middle" class="axis">{_esc(label)}</text>'
        )
    yticks = []
    for frac in (0.0, 0.5, 1.0):
        v = lo + frac * span
        _, y = xy(0, v)
        yticks.append(
            f'<line x1="{pad_l}" x2="{w - pad_r}" y1="{y:.1f}" y2="{y:.1f}" class="gridline"/>'
            f'<text x="{pad_l - 6}" y="{y:.1f}" text-anchor="end" dominant-baseline="middle" class="axis">'
            f'{v:.0f}</text>'
        )
    zero = ""
    if lo < 0 < hi:
        zero = f'<line x1="{pad_l}" x2="{w - pad_r}" y1="{zero_y:.1f}" y2="{zero_y:.1f}" class="zero"/>'

    legend_html = "".join(f'<span class="leg">{x}</span>' for x in legend)
    d0, d1 = _esc(dates[0]), _esc(dates[-1])
    return (
        f'<div class="legend">{legend_html}</div>'
        f'<svg viewBox="0 0 {w} {h}" class="chart" role="img" '
        f'aria-label="Open-trade unrealized P&amp;L in dollars">'
        f"{''.join(yticks)}{zero}{''.join(paths)}{''.join(xticks)}</svg>"
        f'<p class="caption">Unrealized P&amp;L ($) at conservative fill · live marks only '
        f"(carried-forward days omitted) · {d0} to {d1}</p>"
    )


def render_html(snap: dict) -> str:
    n_need = snap["min_n"]
    n_closed = snap["n_closed"]
    n_legacy = snap["n_closed_all_versions"] - n_closed
    legacy_note = (
        f" ({n_legacy} more closed under the pre-Patch-1 simulator, "
        f"mc_terminal_v1 — excluded from Brier/AUC, see table below)" if n_legacy else ""
    )
    if snap["sufficient"]:
        banner = (
            f"<div class='ok'>Calibration sample is live: n={n_closed} closed "
            f"under mc_path_v2 (threshold {n_need}){legacy_note}.</div>"
        )
        brier_s = f"{snap['brier']:.4f}" if snap["brier"] is not None else "n/a"
        auc_s = f"{snap['auc']:.3f}" if snap["auc"] is not None else "n/a"
    else:
        banner = (
            f"<div class='warn'><strong>Too early to score the model.</strong> "
            f"Kelly-regime Brier needs n={n_need} closed trades under the current "
            f"simulator (mc_path_v2). You have n={n_closed}{legacy_note}. "
            f"v1 ({REGIME_V1}) excluded: {snap.get('n_v1_closed', 0)} closed / "
            f"{snap.get('n_v1_forecasts', 0)} forecasts. "
            f"P&amp;L is noisy until n≈100.</div>"
        )
        brier_s = f"insufficient (n={n_closed})"
        auc_s = f"insufficient (n={n_closed})"

    trade_trs = []
    for t in snap["trades"]:
        cls = "row-closed" if t["source"] == "closed" else "row-open"
        if t["same_day_sl"]:
            cls = "row-artifact"
        status = t["status"]
        if t["exit_reason"]:
            status = f"{status} / {t['exit_reason']}"
        trade_trs.append(
            "<tr class='{}'><td>{}</td><td>{}</td><td>{}</td><td class='num'>{}</td>"
            "<td class='num'>{}</td><td class='num'>{}</td><td class='num'>{}</td>"
            "<td class='num'>{}</td><td>{}</td></tr>".format(
                cls,
                _esc(t["ticker"]),
                _esc(t["opened"]),
                _esc(status),
                _esc(_p(t["model_p"])),
                _esc(_money(t["entry_debit"]).replace("$", "")),
                _esc("—" if t["entry_mid"] is None else f"{t['entry_mid']:.3f}"),
                _esc("—" if t["last_cons"] is None else f"{t['last_cons']:.3f}"),
                _esc(_money(t["pnl"])),
                _esc(t["note"] or "—"),
            )
        )

    skip_html = _bars(snap["skip_rows"])
    hist_labels = ["0.10–0.20", "0.20–0.30", "0.30–0.40", "≥ 0.40"]
    hist_html = _bars(list(zip(hist_labels, snap["p_hist"])))
    mtm_html = _svg_mtm(snap["mtm_dates"], snap["mtm_series"])
    if not mtm_html:
        mtm_html = "<p class='muted'>No live marks for open trades yet.</p>"

    mean_p = "—" if snap["mean_p"] is None else f"{snap['mean_p']:.3f}"
    hit = _pct(snap["hit_rate"])
    closed_pnl = _money(snap["closed_pnl"]) if snap["closed_pnl"] is not None else "—"

    mv_trs = []
    for r in snap["model_version_rows"]:
        mv_trs.append(
            "<tr><td>{}</td><td class='num'>{}</td><td class='num'>{}</td><td class='num'>{}</td></tr>".format(
                _esc(r["version"]), r["n"],
                _esc(_pct(r["hit"])) if r["hit"] is not None else "—",
                f"{r['brier']:.4f}" if r["brier"] is not None else ("—" if r["n"] == 0 else f"n&lt;{MIN_N}"),
            )
        )

    hyp_trs = []
    for r in snap["hypothesis_rows"]:
        hyp_trs.append(
            "<tr><td>{}</td><td class='num'>{}</td><td class='num'>{}</td>"
            "<td class='num'>{}</td><td class='num'>{}</td></tr>".format(
                _esc(r["h"]), r["n"],
                _esc(_pct(r["hit"])) if r["hit"] is not None else "—",
                f"{r['mean_pred']:.3f}" if r["mean_pred"] is not None else "—",
                (f"{r['brier']:.4f}" if r["brier"] is not None
                 else ("insufficient" if r["n"] < MIN_N_HYPOTHESIS else f"n&lt;{MIN_N}")),
            )
        )

    exit_labels = {"tp": "TP", "sl": "SL", "time_stop": "Time stop", "expiry": "Expiry", "unknown": "Unknown"}
    exit_html = _bars([(exit_labels.get(k, k), v) for k, v in snap["exit_rows"]])

    def _finite_or_dash(x, fmt):
        try:
            xf = float(x)
            return fmt.format(xf) if xf == xf else "—"  # NaN != NaN
        except (TypeError, ValueError):
            return "—"

    gate_trs = []
    for r in snap["gate_rows"]:
        badge = "pass" if r["passed"] else "fail"
        badge_text = "PASS" if r["passed"] else ("ERR" if r["passed"] is None else "FAIL")
        rvp = _finite_or_dash(r["rv_pctile"], "{:.0f}")
        ivrv = _finite_or_dash(r["iv_rv"], "{:+.3f}")
        gate_trs.append(
            "<tr><td>{}</td><td><span class='pill {}'>{}</span></td>"
            "<td class='num'>{}</td><td class='num'>{}</td><td>{}</td></tr>".format(
                _esc(r["ticker"]), badge, badge_text, rvp, ivrv, _esc(r["reason"]),
            )
        )

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>Paper model dashboard</title>
<style>
  :root {{
    --bg: #1b1b1f; --fg: #e8e8ed; --muted: #9b9ba3; --dim: #6e6e76;
    --line: #2e2e36; --card: #232329; --warn: #3d2a14; --warn-fg: #f0c674;
    --ok: #1c3224; --ok-fg: #9ece6a; --neg: #f7768e; --pos: #9ece6a;
    --fill: #3d5a80; --zero: #56565e;
  }}
  * {{ box-sizing: border-box; }}
  body {{
    margin: 0; padding: 32px 24px 64px;
    font: 14px/1.5 ui-sans-serif, system-ui, -apple-system, sans-serif;
    background: var(--bg); color: var(--fg);
  }}
  main {{ max-width: 960px; margin: 0 auto; }}
  h1 {{ font-size: 22px; font-weight: 600; margin: 0 0 4px; }}
  h2 {{ font-size: 15px; font-weight: 600; margin: 28px 0 10px; }}
  .sub {{ color: var(--muted); font-size: 13px; margin: 0 0 20px; }}
  .warn, .ok {{
    padding: 12px 14px; border-radius: 8px; margin: 16px 0 20px; font-size: 13px;
  }}
  .warn {{ background: var(--warn); color: var(--warn-fg); }}
  .ok {{ background: var(--ok); color: var(--ok-fg); }}
  .stats {{
    display: grid; grid-template-columns: repeat(4, 1fr); gap: 12px; margin: 16px 0 8px;
  }}
  @media (max-width: 720px) {{ .stats {{ grid-template-columns: 1fr 1fr; }} }}
  .stat {{ background: var(--card); border: 1px solid var(--line); border-radius: 8px; padding: 12px 14px; }}
  .stat .v {{ font-size: 22px; font-weight: 600; letter-spacing: -0.02em; }}
  .stat .l {{ color: var(--muted); font-size: 12px; margin-top: 2px; }}
  .neg {{ color: var(--neg); }}
  table {{ width: 100%; border-collapse: collapse; font-size: 13px; }}
  th, td {{ text-align: left; padding: 7px 8px; border-bottom: 1px solid var(--line); }}
  th {{ color: var(--muted); font-weight: 500; font-size: 11px; text-transform: uppercase; letter-spacing: 0.04em; }}
  td.num {{ text-align: right; font-variant-numeric: tabular-nums; }}
  tr.row-artifact td {{ color: var(--neg); }}
  .bar-row {{ display: grid; grid-template-columns: 180px 1fr 36px; gap: 8px; align-items: center; margin: 6px 0; }}
  .bar-label {{ color: var(--muted); font-size: 12px; }}
  .bar-track {{ height: 10px; background: var(--line); border-radius: 4px; overflow: hidden; }}
  .bar-fill {{ height: 100%; background: var(--fill); }}
  .bar-n {{ text-align: right; font-variant-numeric: tabular-nums; font-size: 12px; }}
  .two {{ display: grid; grid-template-columns: 1fr 1fr; gap: 28px; }}
  @media (max-width: 720px) {{ .two {{ grid-template-columns: 1fr; }} }}
  svg.chart {{ width: 100%; height: auto; display: block; }}
  .axis {{ fill: var(--dim); font-size: 11px; font-family: inherit; }}
  .gridline {{ stroke: var(--line); stroke-width: 1; }}
  .zero {{ stroke: var(--zero); stroke-dasharray: 4 3; }}
  .legend {{ display: flex; gap: 14px; flex-wrap: wrap; font-size: 12px; color: var(--muted); margin-bottom: 6px; }}
  .leg {{ display: inline-flex; align-items: center; gap: 6px; }}
  .swatch {{ width: 8px; height: 8px; border-radius: 2px; display: inline-block; }}
  .caption, .muted {{ color: var(--dim); font-size: 12px; margin: 6px 0 0; }}
  .card {{ background: var(--card); border: 1px solid var(--line); border-radius: 8px; padding: 14px 16px; margin-top: 28px; }}
  .card h2 {{ margin-top: 0; }}
  code {{ font: 12px/1.4 ui-monospace, Menlo, monospace; background: #2a2a32; padding: 1px 5px; border-radius: 4px; }}
  ol.metrics {{ margin: 8px 0 0; padding-left: 18px; color: var(--muted); font-size: 13px; }}
  ol.metrics li {{ margin: 4px 0; }}
  .pill {{ display: inline-block; padding: 2px 8px; border-radius: 999px; font-size: 11px; font-weight: 600; letter-spacing: 0.03em; }}
  .pill.pass {{ background: var(--ok); color: var(--ok-fg); }}
  .pill.fail {{ background: var(--warn); color: var(--warn-fg); }}
  .three {{ display: grid; grid-template-columns: 1fr 1fr 1fr; gap: 24px; }}
  @media (max-width: 900px) {{ .three {{ grid-template-columns: 1fr; }} }}
</style>
</head>
<body>
<main>
  <h1>Paper model dashboard</h1>
  <p class="sub">Generated { _esc(snap["generated_utc"]) } · Kelly regime, model_version=mc_path_v2 · forecasts { _esc(snap["date_range"]) } ·
     v1 book + pre-Patch-1 sim excluded from headline Brier · open after <code>git pull</code> or <code>python -m paper dashboard</code></p>
  {banner}

  <div class="stats">
    <div class="stat"><div class="v">{n_closed} / {n_need}</div><div class="l">Closed vs Brier threshold</div></div>
    <div class="stat"><div class="v">{snap["n_wanted_trade"]}</div><div class="l">Model TRADE verdicts ({snap["n_wanted_trade"] - snap["n_wanted_skipped"]} taken)</div></div>
    <div class="stat"><div class="v { 'neg' if (snap['closed_pnl'] or 0) < 0 else '' }">{_esc(closed_pnl)}</div><div class="l">Closed P&amp;L (n={snap['n_closed_pnl']}, all model_versions)</div></div>
    <div class="stat"><div class="v { 'neg' if snap['unreal'] < 0 else '' }">{_esc(_money(snap['unreal']))}</div><div class="l">Open unrealized ({snap['n_open']} trades)</div></div>
  </div>
  <p class="muted">{snap["n_forecasts"]} forecasts ({snap["n_model_src"]} model-sourced) ·
     mean p={_esc(mean_p)} · p≥0.35: {snap["n_p_ge_35"]} ·
     taken hit rate { _esc(hit) } · deployed {_esc(_money(snap["deployed"]))} of {_esc(_money(PORTFOLIO))}</p>

  <h2>Today's cheapness screen</h2>
  <p class="caption">Live signals.cheapness_gate() per ticker · RV%ile ≤40 AND IV-RV ≤+0.03 AND
     (IV rank ≤30 once ≥180d history, ignored until then) · source: underlying_history.csv + chain_history.csv, not historical</p>
  <table>
    <thead><tr><th>Ticker</th><th>Gate</th><th class="num">RV %ile</th><th class="num">IV-RV</th><th>Reason</th></tr></thead>
    <tbody>
      {''.join(gate_trs) if gate_trs else '<tr><td colspan="5" class="muted">No screen data (missing underlying_history/chain_history)</td></tr>'}
    </tbody>
  </table>

  <h2>All paper trades</h2>
  <p class="caption">Conservative fill vs mid · SL = 50% of entry debit · source: data/trades.csv + data/marks.csv</p>
  <table>
    <thead><tr>
      <th>Ticker</th><th>Opened</th><th>Status</th><th class="num">Model p</th>
      <th class="num">Debit</th><th class="num">Entry mid</th><th class="num">Last mark</th>
      <th class="num">P&amp;L</th><th>Note</th>
    </tr></thead>
    <tbody>
      {''.join(trade_trs) if trade_trs else '<tr><td colspan="9" class="muted">No trades yet</td></tr>'}
    </tbody>
  </table>

  <h2>Open-book mark-to-market</h2>
  {mtm_html}

  <div class="three">
    <div>
      <h2>Why names are skipped</h2>
      <p class="caption">Skip reason counts · n={snap["n_skips"]} · source: data/forecasts.csv</p>
      {skip_html}
    </div>
    <div>
      <h2>Model P(profit) distribution</h2>
      <p class="caption">Forecast counts by predicted probability · TRADE threshold 0.35</p>
      {hist_html}
    </div>
    <div>
      <h2>How closed trades exit</h2>
      <p class="caption">TP / SL / time_stop / expiry mix · kelly regime, all model_versions</p>
      {exit_html if snap["exit_rows"] else "<p class='muted'>No closed trades yet</p>"}
    </div>
  </div>

  <h2>Calibration by model_version (Patch 1)</h2>
  <p class="caption">mc_terminal_v1 = pre-Patch-1 (biased terminal-only MC), never re-scored · mc_path_v2 = current, path-dependent</p>
  <table>
    <thead><tr><th>model_version</th><th class="num">n</th><th class="num">Hit rate</th><th class="num">Brier</th></tr></thead>
    <tbody>{''.join(mv_trs)}</tbody>
  </table>

  <h2>Calibration by hypothesis (Patch 3)</h2>
  <p class="caption">mc_path_v2 only · insufficient sample below n={MIN_N_HYPOTHESIS} · formal Brier still needs n={MIN_N}</p>
  <table>
    <thead><tr><th>Hypothesis</th><th class="num">n</th><th class="num">Hit rate</th><th class="num">Mean pred p</th><th class="num">Brier</th></tr></thead>
    <tbody>{''.join(hyp_trs)}</tbody>
  </table>

  <div class="card">
    <h2>How you will know later</h2>
    <p class="muted">Brier { _esc(brier_s) } · AUC { _esc(auc_s) }. Primary metrics, in order:</p>
    <ol class="metrics">
      <li><strong>Brier</strong> — model vs realized win; lower is better. Ready at n={n_need} closed (mc_path_v2 only).</li>
      <li><strong>Calibration curve</strong> — trades called ~36% should win ~36% of the time.</li>
      <li><strong>AUC</strong> — higher-p trades win more often than lower-p trades.</li>
      <li><strong>Per model_version</strong> — confirms the pre-Patch-1 book isn't leaking into the headline.</li>
      <li><strong>Per hypothesis</strong> — which trade ideas are actually working, not just "is the model good".</li>
      <li><strong>Skip analysis</strong> — taken hit rate vs skipped counterfactuals.</li>
      <li><strong>Overrides</strong> — human overrides vs model-approved.</li>
      <li><strong>P&amp;L</strong> — last, ignore until ~100 closes.</li>
    </ol>
  </div>
</main>
</body>
</html>
"""


def write_dashboard(path: Optional[Path] = None) -> Path:
    ensure_data_dir()
    path = path or (DATA / "dashboard.html")
    path.write_text(render_html(snapshot()), encoding="utf-8")
    return path
